#
##database connection
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/LD-217
#    username: root
#    password: 123456789
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #changing default username and password
#  security:
#    user:
#      name: user
#      password: password
##JPA settings
#  jpa:
#    hibernate:
#      ddl-auto: create
#      show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
